In [1]:
import pandas as pd 
import numpy as np

In [2]:
#1st Dataset from kaggle

https://www.kaggle.com/datasets/saurabhshahane/fake-news-classification

In [3]:
df_wf=pd.read_csv("WELFake_Dataset.csv")

In [4]:
df_wf = df_wf.dropna(subset=['title', 'label'])

# Verify the shape after dropping NaNs
print(f"Dataset after dropping NaNs: {df_wf.shape}")

Dataset after dropping NaNs: (71576, 4)

In [5]:
label_mapping = {
    1: "__label__fake",
    0: "__label__real"
}
df_wf['label'] = df_wf['label'].map(label_mapping)

import re

def clean_text(text):
    text = re.sub(r'[^\w\s]', '', text)  # Remove special characters
    text = re.sub(r'\s+', ' ', text)  # Replace multiple spaces with a single space
    return text.strip().lower()  


df_wf['cleaned_title'] = df_wf['title'].apply(clean_text)


df_wf['fasttext_format'] = df_wf['label'] + ' ' + df_wf['cleaned_title']

df_wf[['fasttext_format']].head()

                                     fasttext_format
0  __label__fake law enforcement on high alert fo...
2  __label__fake unbelievable obamas attorney gen...
3  __label__real bobby jindal raised hindu uses s...
4  __label__fake satan 2 russia unvelis an image ...
5  __label__fake about time christian group sues ...

In [6]:
df_wf.shape

(71576, 6)

In [7]:
df_wf["label"].value_counts()

__label__fake    36548
__label__real    35028
Name: label, dtype: int64

In [8]:
df_wf_1= df_wf[["label","fasttext_format"]]

In [9]:
df_wf_1

               label                                    fasttext_format
0      __label__fake  __label__fake law enforcement on high alert fo...
2      __label__fake  __label__fake unbelievable obamas attorney gen...
3      __label__real  __label__real bobby jindal raised hindu uses s...
4      __label__fake  __label__fake satan 2 russia unvelis an image ...
5      __label__fake  __label__fake about time christian group sues ...
...              ...                                                ...
72129  __label__real  __label__real russians steal research on trump...
72130  __label__fake  __label__fake watch giuliani demands that demo...
72131  __label__real  __label__real migrants refuse to leave train a...
72132  __label__real  __label__real trump tussle gives unpopular mex...
72133  __label__fake  __label__fake goldman sachs endorses hillary c...

[71576 rows x 2 columns]

In [10]:
#2nd and 3rd dataset from kaggle containing true and fake news.

In [11]:
true=pd.read_csv("True.csv")

In [12]:
fake=pd.read_csv("Fake.csv")

In [13]:
df_true = pd.read_csv('True.csv')
df_fake = pd.read_csv('Fake.csv')


df_true['label'] = 'True'
df_fake['label'] = 'Fake'


merged_df = pd.concat([df_true, df_fake], ignore_index=True)


print(merged_df.head())

                                               title  \
0  As U.S. budget fight looms, Republicans flip t...
1  U.S. military to accept transgender recruits o...
2  Senior U.S. Republican senator: 'Let Mr. Muell...
3  FBI Russia probe helped by Australian diplomat...
4  Trump wants Postal Service to charge 'much mor...

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews
2  WASHINGTON (Reuters) - The special counsel inv...  politicsNews
3  WASHINGTON (Reuters) - Trump campaign adviser ...  politicsNews
4  SEATTLE/WASHINGTON (Reuters) - President Donal...  politicsNews

                 date label
0  December 31, 2017   True
1  December 29, 2017   True
2  December 31, 2017   True
3  December 30, 2017   True
4  December 29, 2017   True

In [14]:
merged_df.drop(["text","subject","date"],axis=1,inplace=True)

In [15]:
merged_df

                                                   title label
0      As U.S. budget fight looms, Republicans flip t...  True
1      U.S. military to accept transgender recruits o...  True
2      Senior U.S. Republican senator: 'Let Mr. Muell...  True
3      FBI Russia probe helped by Australian diplomat...  True
4      Trump wants Postal Service to charge 'much mor...  True
...                                                  ...   ...
44893  McPain: John McCain Furious That Iran Treated ...  Fake
44894  JUSTICE? Yahoo Settles E-mail Privacy Class-ac...  Fake
44895  Sunnistan: US and Allied â€˜Safe Zoneâ€™ Plan to T...  Fake
44896  How to Blow $700 Million: Al Jazeera America F...  Fake
44897  10 U.S. Navy Sailors Held by Iranian Military ...  Fake

[44898 rows x 2 columns]

In [16]:
sampled_df = merged_df.sample(frac=0.8, random_state=10)

print(f"Sampled Data Shape: {sampled_df.shape}")

Sampled Data Shape: (35918, 2)

In [17]:
sampled_df

                                                   title label
3040   Top Senate Democrat Schumer: 50-50 chance Repu...  True
41612  SWEDISH WOMAN Sexually Assaulted In Broad Dayl...  Fake
6040   White House says no curb on federal agency med...  True
30742  JUST IN: Why Anchor #MattLauer Was Just Fired ...  Fake
19492  Militant attack on minister's convoy kills two...  True
...                                                  ...   ...
29560   Anti-Obama ESPN Host Cuts Off Singer As He Be...  Fake
41527  MUST SEE: House Oversight Committee Releases M...  Fake
23866   Mike Pence Breaks Silence, Responds To Being ...  Fake
43575          What Is Going On With The Secret Service?  Fake
8716   For Islamophobia, take two of these and call a...  True

[35918 rows x 2 columns]

In [18]:
sampled_df['label'] = sampled_df['label'].replace('True', 'real')

In [19]:
sampled_df['label'] = sampled_df['label'].replace('Fake', 'fake')

In [20]:
sampled_df

                                                   title label
3040   Top Senate Democrat Schumer: 50-50 chance Repu...  real
41612  SWEDISH WOMAN Sexually Assaulted In Broad Dayl...  fake
6040   White House says no curb on federal agency med...  real
30742  JUST IN: Why Anchor #MattLauer Was Just Fired ...  fake
19492  Militant attack on minister's convoy kills two...  real
...                                                  ...   ...
29560   Anti-Obama ESPN Host Cuts Off Singer As He Be...  fake
41527  MUST SEE: House Oversight Committee Releases M...  fake
23866   Mike Pence Breaks Silence, Responds To Being ...  fake
43575          What Is Going On With The Secret Service?  fake
8716   For Islamophobia, take two of these and call a...  real

[35918 rows x 2 columns]

In [21]:
# Apply the cleaning function to the 'text' column
label_mapping = {
    "fake": "__label__fake",
    "real": "__label__real"
}
sampled_df['label'] = sampled_df['label'].map(label_mapping)

import re

def clean_text(text):
    text = re.sub(r'[^\w\s]', '', text)  # Remove special characters
    text = re.sub(r'\s+', ' ', text)  # Replace multiple spaces with a single space
    return text.strip().lower()  # Convert to lowercase and strip spaces

sampled_df['cleaned_title'] = sampled_df['title'].apply(clean_text)


sampled_df['fasttext_format'] = sampled_df['label'] + ' ' + sampled_df['cleaned_title']


sampled_df['fasttext_format'] = sampled_df['label'] + ' ' + sampled_df['cleaned_title']

In [22]:
sampled_df

,title,label,cleaned_title,fasttext_format
3040,Top Senate Democrat Schumer: 50-50 chance Repu...,__label__real,top senate democrat schumer 5050 chance republ...,__label__real top senate democrat schumer 5050...
41612,SWEDISH WOMAN Sexually Assaulted In Broad Dayl...,__label__fake,swedish woman sexually assaulted in broad dayl...,__label__fake swedish woman sexually assaulted...
6040,White House says no curb on federal agency med...,__label__real,white house says no curb on federal agency med...,__label__real white house says no curb on fede...
30742,JUST IN: Why Anchor #MattLauer Was Just Fired ...,__label__fake,just in why anchor mattlauer was just fired af...,__label__fake just in why anchor mattlauer was...
19492,Militant attack on minister's convoy kills two...,__label__real,militant attack on ministers convoy kills two ...,__label__real militant attack on ministers con...
...,...,...,...,...
29560,Anti-Obama ESPN Host Cuts Off Singer As He Be...,__label__fake,antiobama espn host cuts off singer as he begi...,__label__fake antiobama espn host cuts off sin...
41527,MUST SEE: House Oversight Committee Releases M...,__label__fake,must see house oversight committee releases mo...,__label__fake must see house oversight committ...
23866,"Mike Pence Breaks Silence, Responds To Being ...",__label__fake,mike pence breaks silence responds to being mi...,__label__fake mike pence breaks silence respon...
43575,What Is Going On With The Secret Service?,__label__fake,what is going on with the secret service,__label__fake what is going on with the secret...
8716,"For Islamophobia, take two of these and call a...",__label__real,for islamophobia take two of these and call a ...,__label__real for islamophobia take two of the...

In [23]:
sampled_df_1=sampled_df[["fasttext_format"]]

In [24]:
df_wf_10=df_wf_1[["fasttext_format"]]

In [25]:
df_wf_10

                                         fasttext_format
0      __label__fake law enforcement on high alert fo...
2      __label__fake unbelievable obamas attorney gen...
3      __label__real bobby jindal raised hindu uses s...
4      __label__fake satan 2 russia unvelis an image ...
5      __label__fake about time christian group sues ...
...                                                  ...
72129  __label__real russians steal research on trump...
72130  __label__fake watch giuliani demands that demo...
72131  __label__real migrants refuse to leave train a...
72132  __label__real trump tussle gives unpopular mex...
72133  __label__fake goldman sachs endorses hillary c...

[71576 rows x 1 columns]

In [26]:
sampled_df_1

                                         fasttext_format
3040   __label__real top senate democrat schumer 5050...
41612  __label__fake swedish woman sexually assaulted...
6040   __label__real white house says no curb on fede...
30742  __label__fake just in why anchor mattlauer was...
19492  __label__real militant attack on ministers con...
...                                                  ...
29560  __label__fake antiobama espn host cuts off sin...
41527  __label__fake must see house oversight committ...
23866  __label__fake mike pence breaks silence respon...
43575  __label__fake what is going on with the secret...
8716   __label__real for islamophobia take two of the...

[35918 rows x 1 columns]

In [27]:
df_wf_10

                                         fasttext_format
0      __label__fake law enforcement on high alert fo...
2      __label__fake unbelievable obamas attorney gen...
3      __label__real bobby jindal raised hindu uses s...
4      __label__fake satan 2 russia unvelis an image ...
5      __label__fake about time christian group sues ...
...                                                  ...
72129  __label__real russians steal research on trump...
72130  __label__fake watch giuliani demands that demo...
72131  __label__real migrants refuse to leave train a...
72132  __label__real trump tussle gives unpopular mex...
72133  __label__fake goldman sachs endorses hillary c...

[71576 rows x 1 columns]

In [28]:
#mering all the datasets together 

merged_data_final = pd.concat([df_wf_10, sampled_df_1], ignore_index=True)

# Display the merged DataFrame to confirm
merged_data_final.head()

                                     fasttext_format
0  __label__fake law enforcement on high alert fo...
1  __label__fake unbelievable obamas attorney gen...
2  __label__real bobby jindal raised hindu uses s...
3  __label__fake satan 2 russia unvelis an image ...
4  __label__fake about time christian group sues ...

In [29]:
merged_data_final.shape

(107494, 1)

In [30]:
final_data = merged_data_final.sample(frac=0.90, random_state=11)

In [31]:
final_data

                                          fasttext_format
25292   __label__real trump calls court decision block...
31689   __label__fake al sharpton blames racism for tr...
23496   __label__real clinton campaign denies staffing...
39191   __label__fake series of powerful earthquakes i...
73938   __label__real obama tells trump to stop whinin...
...                                                   ...
43224   __label__fake shut it down judicial watch pres...
35007   __label__fake bernie sanders asks one question...
103899  __label__real nepal to elect new parliament af...
50647   __label__real source baltimore mayor ordered p...
97278   __label__real ican leader delighted with nobel...

[96745 rows x 1 columns]

In [32]:
from sklearn.model_selection import train_test_split
train, test = train_test_split(final_data,test_size=0.3)

In [33]:
train.to_csv("news_data_train_final_title.txt",columns=['fasttext_format'],index=False,header=False)
test.to_csv("news_data_test_final_title.txt",columns=['fasttext_format'],index=False,header=False)